// Form field configurations for each MIS document type
// Each document type has unique fields stored as JSONB in the `data` column

export interface FormField {
  key: string;
  label: string;
  type: 'text' | 'textarea' | 'number' | 'date' | 'select' | 'checkbox' | 'percentage';
  placeholder?: string;
  options?: { label: string; value: string }[];
  required?: boolean;
  defaultValue?: any;
}

export interface DocumentTypeConfig {
  documentType: string;
  number: number;
  title: string;
  linkTo: 'style' | 'date' | 'line' | 'style_line' | 'none';
  fields: FormField[];
}

const STATUS_OPTIONS = [
  { label: 'Pending', value: 'pending' },
  { label: 'In Progress', value: 'in_progress' },
  { label: 'Completed', value: 'completed' },
  { label: 'Approved', value: 'approved' },
  { label: 'Rejected', value: 'rejected' },
  { label: 'N/A', value: 'na' },
];

const APPROVAL_OPTIONS = [
  { label: 'Pending', value: 'pending' },
  { label: 'Approved', value: 'approved' },
  { label: 'Approved with Comments', value: 'approved_comments' },
  { label: 'Rejected', value: 'rejected' },
];

const GRADE_OPTIONS = [
  { label: 'Pass', value: 'pass' },
  { label: 'Fail', value: 'fail' },
  { label: 'Conditional', value: 'conditional' },
];

export const PRE_PRODUCTION_CONFIGS: DocumentTypeConfig[] = [
  {
    documentType: 'style_file',
    number: 1,
    title: 'Style File',
    linkTo: 'style',
    fields: [
      { key: 'file_reference', label: 'File Reference No', type: 'text', required: true, placeholder: 'SF-001' },
      { key: 'version', label: 'Version', type: 'text', placeholder: 'v1.0' },
      { key: 'tech_pack_received', label: 'Tech Pack Received', type: 'checkbox' },
      { key: 'tech_pack_date', label: 'Tech Pack Received Date', type: 'date' },
      { key: 'bom_prepared', label: 'BOM Prepared', type: 'checkbox' },
      { key: 'operation_breakdown', label: 'Operation Breakdown Done', type: 'checkbox' },
      { key: 'smv_calculated', label: 'SMV Calculated', type: 'checkbox' },
      { key: 'costing_done', label: 'Costing Done', type: 'checkbox' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
      { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional details...' },
    ],
  },
  {
    documentType: 'qc_qi_instructions',
    number: 2,
    title: 'QC / QI Instructions',
    linkTo: 'style',
    fields: [
      { key: 'instruction_ref', label: 'Instruction Reference', type: 'text', required: true, placeholder: 'QCI-001' },
      { key: 'inspection_type', label: 'Inspection Type', type: 'select', options: [
        { label: 'Inline', value: 'inline' }, { label: 'End Line', value: 'endline' },
        { label: 'Final', value: 'final' }, { label: 'AQL', value: 'aql' },
      ]},
      { key: 'critical_points', label: 'Critical Quality Points', type: 'textarea', placeholder: 'List critical quality checkpoints...' },
      { key: 'measurement_points', label: 'Key Measurement Points', type: 'textarea', placeholder: 'List key measurements...' },
      { key: 'tolerance_specs', label: 'Tolerance Specifications', type: 'textarea' },
      { key: 'visual_standards', label: 'Visual Standards Defined', type: 'checkbox' },
      { key: 'distributed_to_lines', label: 'Distributed to Lines', type: 'checkbox' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'approved_sample',
    number: 3,
    title: 'Approved Sample',
    linkTo: 'style',
    fields: [
      { key: 'sample_type', label: 'Sample Type', type: 'select', required: true, options: [
        { label: 'Proto', value: 'proto' }, { label: 'Fit', value: 'fit' },
        { label: 'Size Set', value: 'size_set' }, { label: 'PP Sample', value: 'pp' },
        { label: 'Production', value: 'production' }, { label: 'Shipment', value: 'shipment' },
      ]},
      { key: 'sample_ref', label: 'Sample Reference', type: 'text', placeholder: 'SMPL-001' },
      { key: 'submitted_date', label: 'Submitted Date', type: 'date' },
      { key: 'approval_date', label: 'Approval Date', type: 'date' },
      { key: 'approved_by', label: 'Approved By', type: 'text', placeholder: 'Buyer QA name' },
      { key: 'comments_received', label: 'Buyer Comments', type: 'textarea' },
      { key: 'seal_sample_available', label: 'Seal Sample Available', type: 'checkbox' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'fabric_trim_card',
    number: 4,
    title: 'Approved Fabric Color Continuity Card & Trim Card',
    linkTo: 'style',
    fields: [
      { key: 'fabric_card_ref', label: 'Fabric Card Reference', type: 'text', required: true },
      { key: 'trim_card_ref', label: 'Trim Card Reference', type: 'text', required: true },
      { key: 'fabric_type', label: 'Fabric Type', type: 'text', placeholder: 'e.g., 100% Cotton Denim' },
      { key: 'fabric_color', label: 'Fabric Color', type: 'text' },
      { key: 'color_lot_no', label: 'Color Lot No', type: 'text' },
      { key: 'shade_band', label: 'Shade Band', type: 'select', options: [
        { label: 'A', value: 'A' }, { label: 'B', value: 'B' },
        { label: 'C', value: 'C' }, { label: 'D', value: 'D' },
      ]},
      { key: 'trim_details', label: 'Trim Details', type: 'textarea', placeholder: 'Buttons, zippers, labels...' },
      { key: 'buyer_approved', label: 'Buyer Approved', type: 'checkbox' },
      { key: 'approval_date', label: 'Approval Date', type: 'date' },
      { key: 'approval_status', label: 'Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'lab_test_report',
    number: 5,
    title: 'Lab Test Report Procedure',
    linkTo: 'style',
    fields: [
      { key: 'test_ref', label: 'Test Reference No', type: 'text', required: true },
      { key: 'test_type', label: 'Test Type', type: 'select', options: [
        { label: 'Shrinkage', value: 'shrinkage' }, { label: 'Color Fastness', value: 'color_fastness' },
        { label: 'Tensile Strength', value: 'tensile' }, { label: 'Pilling', value: 'pilling' },
        { label: 'GSM', value: 'gsm' }, { label: 'pH', value: 'ph' },
        { label: 'Dimensional Stability', value: 'dimensional' }, { label: 'Other', value: 'other' },
      ]},
      { key: 'lab_name', label: 'Lab Name', type: 'text', placeholder: 'Testing laboratory' },
      { key: 'test_date', label: 'Test Date', type: 'date' },
      { key: 'test_result', label: 'Test Result', type: 'select', options: GRADE_OPTIONS },
      { key: 'result_details', label: 'Result Details', type: 'textarea' },
      { key: 'buyer_requirement', label: 'Buyer Requirement/Standard', type: 'text' },
      { key: 'certificate_available', label: 'Certificate Available', type: 'checkbox' },
    ],
  },
  {
    documentType: 'fabric_inspection',
    number: 6,
    title: 'Fabric Inspection',
    linkTo: 'style',
    fields: [
      { key: 'inspection_ref', label: 'Inspection Reference', type: 'text', required: true },
      { key: 'fabric_type', label: 'Fabric Type', type: 'text', required: true },
      { key: 'roll_no', label: 'Roll No / Lot No', type: 'text' },
      { key: 'total_meters', label: 'Total Meters Inspected', type: 'number' },
      { key: 'inspection_system', label: 'Inspection System', type: 'select', options: [
        { label: '4-Point System', value: '4_point' }, { label: '10-Point System', value: '10_point' },
      ]},
      { key: 'total_points', label: 'Total Defect Points', type: 'number' },
      { key: 'points_per_100sqm', label: 'Points Per 100 Sq Yards', type: 'number' },
      { key: 'defect_types', label: 'Defect Types Found', type: 'textarea', placeholder: 'Holes, stains, shade variation...' },
      { key: 'pass_fail', label: 'Result', type: 'select', options: GRADE_OPTIONS },
      { key: 'inspected_by', label: 'Inspected By', type: 'text' },
    ],
  },
  {
    documentType: 'trim_inspection',
    number: 7,
    title: 'Trim Inspection',
    linkTo: 'style',
    fields: [
      { key: 'inspection_ref', label: 'Inspection Reference', type: 'text', required: true },
      { key: 'trim_type', label: 'Trim Type', type: 'select', options: [
        { label: 'Button', value: 'button' }, { label: 'Zipper', value: 'zipper' },
        { label: 'Label', value: 'label' }, { label: 'Thread', value: 'thread' },
        { label: 'Rivet', value: 'rivet' }, { label: 'Snap', value: 'snap' },
        { label: 'Elastic', value: 'elastic' }, { label: 'Other', value: 'other' },
      ]},
      { key: 'qty_received', label: 'Qty Received', type: 'number' },
      { key: 'qty_inspected', label: 'Qty Inspected', type: 'number' },
      { key: 'defects_found', label: 'Defects Found', type: 'number' },
      { key: 'defect_description', label: 'Defect Description', type: 'textarea' },
      { key: 'aql_level', label: 'AQL Level', type: 'select', options: [
        { label: '1.0', value: '1.0' }, { label: '1.5', value: '1.5' },
        { label: '2.5', value: '2.5' }, { label: '4.0', value: '4.0' },
      ]},
      { key: 'pass_fail', label: 'Result', type: 'select', options: GRADE_OPTIONS },
      { key: 'inspected_by', label: 'Inspected By', type: 'text' },
    ],
  },
  {
    documentType: 'calibration_equipment',
    number: 8,
    title: 'Calibration Of Measuring Equipment',
    linkTo: 'date',
    fields: [
      { key: 'equipment_name', label: 'Equipment Name', type: 'text', required: true, placeholder: 'e.g., Measuring Tape' },
      { key: 'equipment_id', label: 'Equipment ID / Serial No', type: 'text', required: true },
      { key: 'location', label: 'Location / Department', type: 'text' },
      { key: 'calibration_date', label: 'Calibration Date', type: 'date' },
      { key: 'next_due_date', label: 'Next Due Date', type: 'date' },
      { key: 'calibrated_by', label: 'Calibrated By', type: 'text' },
      { key: 'calibration_result', label: 'Calibration Result', type: 'select', options: GRADE_OPTIONS },
      { key: 'certificate_no', label: 'Certificate No', type: 'text' },
      { key: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  {
    documentType: 'fabric_shrinkage',
    number: 9,
    title: 'Fabric Shrinkage Report',
    linkTo: 'style',
    fields: [
      { key: 'fabric_type', label: 'Fabric Type', type: 'text', required: true },
      { key: 'lot_no', label: 'Lot / Roll No', type: 'text' },
      { key: 'test_method', label: 'Test Method', type: 'select', options: [
        { label: 'Washing', value: 'washing' }, { label: 'Steaming', value: 'steaming' },
        { label: 'Fusing', value: 'fusing' }, { label: 'Dry Clean', value: 'dry_clean' },
      ]},
      { key: 'warp_before', label: 'Warp Before (cm)', type: 'number' },
      { key: 'warp_after', label: 'Warp After (cm)', type: 'number' },
      { key: 'warp_shrinkage', label: 'Warp Shrinkage %', type: 'percentage' },
      { key: 'weft_before', label: 'Weft Before (cm)', type: 'number' },
      { key: 'weft_after', label: 'Weft After (cm)', type: 'number' },
      { key: 'weft_shrinkage', label: 'Weft Shrinkage %', type: 'percentage' },
      { key: 'buyer_tolerance', label: 'Buyer Tolerance %', type: 'percentage' },
      { key: 'result', label: 'Result', type: 'select', options: GRADE_OPTIONS },
    ],
  },
  {
    documentType: 'fabric_segregation',
    number: 10,
    title: 'Fabric Segregation Records',
    linkTo: 'style',
    fields: [
      { key: 'lot_no', label: 'Lot No', type: 'text', required: true },
      { key: 'shade_group', label: 'Shade Group', type: 'select', options: [
        { label: 'A', value: 'A' }, { label: 'B', value: 'B' },
        { label: 'C', value: 'C' }, { label: 'D', value: 'D' },
      ]},
      { key: 'total_rolls', label: 'Total Rolls', type: 'number' },
      { key: 'total_meters', label: 'Total Meters', type: 'number' },
      { key: 'segregated_by_shade', label: 'Segregated By Shade', type: 'checkbox' },
      { key: 'segregated_by_width', label: 'Segregated By Width', type: 'checkbox' },
      { key: 'width_variation', label: 'Width Variation (inches)', type: 'text' },
      { key: 'shade_remarks', label: 'Shade Remarks', type: 'textarea' },
      { key: 'segregated_by', label: 'Segregated By', type: 'text' },
    ],
  },
  {
    documentType: 'cutting_pattern_approval',
    number: 11,
    title: 'Cutting Pattern Approval',
    linkTo: 'style',
    fields: [
      { key: 'pattern_ref', label: 'Pattern Reference', type: 'text', required: true },
      { key: 'sizes', label: 'Sizes', type: 'text', placeholder: 'S, M, L, XL, XXL' },
      { key: 'pattern_maker', label: 'Pattern Maker', type: 'text' },
      { key: 'grading_done', label: 'Grading Done', type: 'checkbox' },
      { key: 'notches_checked', label: 'Notches Checked', type: 'checkbox' },
      { key: 'grain_lines_checked', label: 'Grain Lines Checked', type: 'checkbox' },
      { key: 'seam_allowance_verified', label: 'Seam Allowance Verified', type: 'checkbox' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'approval_date', label: 'Approval Date', type: 'date' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'finish_pattern_marking',
    number: 12,
    title: 'Finish Pattern And Marking Board Approvals',
    linkTo: 'style',
    fields: [
      { key: 'pattern_ref', label: 'Finish Pattern Reference', type: 'text', required: true },
      { key: 'marking_board_ref', label: 'Marking Board Reference', type: 'text' },
      { key: 'sizes_checked', label: 'Sizes Checked', type: 'text', placeholder: 'S, M, L, XL' },
      { key: 'button_marking', label: 'Button Marking Verified', type: 'checkbox' },
      { key: 'pocket_placement', label: 'Pocket Placement Verified', type: 'checkbox' },
      { key: 'label_placement', label: 'Label Placement Verified', type: 'checkbox' },
      { key: 'embroidery_placement', label: 'Embroidery Placement Verified', type: 'checkbox' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'approval_date', label: 'Approval Date', type: 'date' },
      { key: 'approval_status', label: 'Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'line_sample',
    number: 13,
    title: 'Line Sample',
    linkTo: 'style_line',
    fields: [
      { key: 'sample_ref', label: 'Sample Reference', type: 'text', required: true },
      { key: 'sample_size', label: 'Sample Size', type: 'text', placeholder: 'e.g., M' },
      { key: 'sample_qty', label: 'Sample Qty', type: 'number' },
      { key: 'prepared_date', label: 'Prepared Date', type: 'date' },
      { key: 'checked_by_qc', label: 'Checked by QC', type: 'checkbox' },
      { key: 'checked_by_ie', label: 'Checked by IE', type: 'checkbox' },
      { key: 'measurement_ok', label: 'Measurement OK', type: 'checkbox' },
      { key: 'construction_ok', label: 'Construction OK', type: 'checkbox' },
      { key: 'buyer_comments', label: 'Buyer Comments', type: 'textarea' },
      { key: 'approval_status', label: 'Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'measurement_sheet',
    number: 14,
    title: 'Measurement Sheet',
    linkTo: 'style',
    fields: [
      { key: 'measurement_ref', label: 'Measurement Ref', type: 'text', required: true },
      { key: 'size', label: 'Size', type: 'text', required: true, placeholder: 'e.g., M' },
      { key: 'tolerance', label: 'Tolerance (+/-)', type: 'text', placeholder: 'e.g., 0.5 inch' },
      { key: 'chest', label: 'Chest', type: 'text' },
      { key: 'waist', label: 'Waist', type: 'text' },
      { key: 'hip', label: 'Hip', type: 'text' },
      { key: 'inseam', label: 'Inseam', type: 'text' },
      { key: 'outseam', label: 'Outseam', type: 'text' },
      { key: 'body_length', label: 'Body Length', type: 'text' },
      { key: 'sleeve_length', label: 'Sleeve Length', type: 'text' },
      { key: 'shoulder', label: 'Shoulder', type: 'text' },
      { key: 'thigh', label: 'Thigh', type: 'text' },
      { key: 'knee', label: 'Knee', type: 'text' },
      { key: 'bottom_opening', label: 'Bottom Opening', type: 'text' },
      { key: 'additional_measurements', label: 'Additional Measurements', type: 'textarea' },
      { key: 'verified_by', label: 'Verified By', type: 'text' },
    ],
  },
  {
    documentType: 'critical_operation',
    number: 15,
    title: 'Critical Operation Identification',
    linkTo: 'style',
    fields: [
      { key: 'operation_1', label: 'Critical Operation 1', type: 'text', placeholder: 'e.g., Front pocket attach' },
      { key: 'machine_1', label: 'Machine Type 1', type: 'text' },
      { key: 'operation_2', label: 'Critical Operation 2', type: 'text' },
      { key: 'machine_2', label: 'Machine Type 2', type: 'text' },
      { key: 'operation_3', label: 'Critical Operation 3', type: 'text' },
      { key: 'machine_3', label: 'Machine Type 3', type: 'text' },
      { key: 'operation_4', label: 'Critical Operation 4', type: 'text' },
      { key: 'machine_4', label: 'Machine Type 4', type: 'text' },
      { key: 'operation_5', label: 'Critical Operation 5', type: 'text' },
      { key: 'machine_5', label: 'Machine Type 5', type: 'text' },
      { key: 'skill_required', label: 'Special Skill Required', type: 'textarea' },
      { key: 'training_done', label: 'Training Done', type: 'checkbox' },
    ],
  },
  {
    documentType: 'line_layout_manpower',
    number: 16,
    title: 'Line Layout And Manpower Allocation',
    linkTo: 'style_line',
    fields: [
      { key: 'layout_ref', label: 'Layout Reference', type: 'text', required: true },
      { key: 'total_operations', label: 'Total Operations', type: 'number' },
      { key: 'total_operators', label: 'Total Operators', type: 'number' },
      { key: 'total_helpers', label: 'Total Helpers', type: 'number' },
      { key: 'total_machines', label: 'Total Machines', type: 'number' },
      { key: 'smv', label: 'Target SMV', type: 'number' },
      { key: 'target_output', label: 'Target Output/Hour', type: 'number' },
      { key: 'bottleneck_identified', label: 'Bottleneck Operations Identified', type: 'textarea' },
      { key: 'layout_approved', label: 'Layout Approved', type: 'checkbox' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
    ],
  },
  {
    documentType: 'fabric_trim_status',
    number: 17,
    title: 'Fabric & Trim Status Report',
    linkTo: 'style',
    fields: [
      { key: 'fabric_ordered', label: 'Fabric Ordered (meters)', type: 'number' },
      { key: 'fabric_received', label: 'Fabric Received (meters)', type: 'number' },
      { key: 'fabric_inspected', label: 'Fabric Inspected (meters)', type: 'number' },
      { key: 'fabric_status', label: 'Fabric Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'trim_ordered', label: 'Total Trim Items Ordered', type: 'number' },
      { key: 'trim_received', label: 'Trim Items Received', type: 'number' },
      { key: 'trim_pending', label: 'Trim Items Pending', type: 'number' },
      { key: 'trim_status', label: 'Trim Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'shortage_details', label: 'Shortage Details', type: 'textarea' },
      { key: 'eta_pending', label: 'ETA for Pending Items', type: 'date' },
    ],
  },
  {
    documentType: 'pp_meeting',
    number: 18,
    title: 'PP Meeting',
    linkTo: 'style',
    fields: [
      { key: 'meeting_date', label: 'Meeting Date', type: 'date', required: true },
      { key: 'meeting_ref', label: 'Meeting Reference', type: 'text' },
      { key: 'attendees', label: 'Attendees', type: 'textarea', placeholder: 'Names and designations...' },
      { key: 'fabric_status_reviewed', label: 'Fabric Status Reviewed', type: 'checkbox' },
      { key: 'trim_status_reviewed', label: 'Trim Status Reviewed', type: 'checkbox' },
      { key: 'sample_reviewed', label: 'Sample Reviewed', type: 'checkbox' },
      { key: 'production_plan_discussed', label: 'Production Plan Discussed', type: 'checkbox' },
      { key: 'quality_points_discussed', label: 'Quality Points Discussed', type: 'checkbox' },
      { key: 'action_points', label: 'Action Points', type: 'textarea', placeholder: 'List action items...' },
      { key: 'minutes', label: 'Meeting Minutes', type: 'textarea' },
      { key: 'next_meeting_date', label: 'Next Meeting Date', type: 'date' },
    ],
  },
  {
    documentType: 'pp_checklist',
    number: 19,
    title: 'PP Check List',
    linkTo: 'style',
    fields: [
      { key: 'tech_pack_available', label: 'Tech Pack Available', type: 'checkbox' },
      { key: 'approved_sample_available', label: 'Approved Sample Available', type: 'checkbox' },
      { key: 'fabric_approved', label: 'Fabric Approved', type: 'checkbox' },
      { key: 'trims_approved', label: 'Trims Approved', type: 'checkbox' },
      { key: 'pattern_approved', label: 'Pattern Approved', type: 'checkbox' },
      { key: 'measurement_spec_available', label: 'Measurement Spec Available', type: 'checkbox' },
      { key: 'shrinkage_report_done', label: 'Shrinkage Report Done', type: 'checkbox' },
      { key: 'lab_test_done', label: 'Lab Test Done', type: 'checkbox' },
      { key: 'bom_confirmed', label: 'BOM Confirmed', type: 'checkbox' },
      { key: 'line_layout_ready', label: 'Line Layout Ready', type: 'checkbox' },
      { key: 'manpower_allocated', label: 'Manpower Allocated', type: 'checkbox' },
      { key: 'risk_assessment', label: 'Risk Assessment Done', type: 'checkbox' },
      { key: 'pp_meeting_done', label: 'PP Meeting Done', type: 'checkbox' },
      { key: 'overall_readiness', label: 'Overall Readiness', type: 'percentage' },
      { key: 'checklist_approved_by', label: 'Approved By', type: 'text' },
    ],
  },
  {
    documentType: 'size_set_pilot_cut',
    number: 20,
    title: 'Size Set / Pilot Cut Approval',
    linkTo: 'style',
    fields: [
      { key: 'pilot_ref', label: 'Pilot Cut Reference', type: 'text', required: true },
      { key: 'sizes_cut', label: 'Sizes Cut', type: 'text', placeholder: 'S, M, L, XL' },
      { key: 'qty_per_size', label: 'Qty Per Size', type: 'number' },
      { key: 'cut_date', label: 'Cut Date', type: 'date' },
      { key: 'fabric_used', label: 'Fabric Used', type: 'text' },
      { key: 'sewing_completed', label: 'Sewing Completed', type: 'checkbox' },
      { key: 'measurement_checked', label: 'Measurement Checked', type: 'checkbox' },
      { key: 'fit_approved', label: 'Fit Approved', type: 'checkbox' },
      { key: 'construction_approved', label: 'Construction Approved', type: 'checkbox' },
      { key: 'wash_test_done', label: 'Wash Test Done', type: 'checkbox' },
      { key: 'defects_found', label: 'Defects Found', type: 'textarea' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'approval_status', label: 'Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
];

export const CUTTING_PRODUCTION_CONFIGS: DocumentTypeConfig[] = [
  {
    documentType: 'cut_dept_structure',
    number: 21,
    title: 'Department Structure & Manpower Budget',
    linkTo: 'date',
    fields: [
      { key: 'department', label: 'Department', type: 'text', required: true, defaultValue: 'Cutting' },
      { key: 'total_manpower', label: 'Total Manpower', type: 'number' },
      { key: 'operators', label: 'Operators', type: 'number' },
      { key: 'helpers', label: 'Helpers', type: 'number' },
      { key: 'supervisors', label: 'Supervisors', type: 'number' },
      { key: 'qc_staff', label: 'QC Staff', type: 'number' },
      { key: 'budgeted_manpower', label: 'Budgeted Manpower', type: 'number' },
      { key: 'variance', label: 'Variance', type: 'number' },
      { key: 'org_chart_available', label: 'Org Chart Available', type: 'checkbox' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    documentType: 'cut_attendance',
    number: 22,
    title: 'Section Attendance Register',
    linkTo: 'date',
    fields: [
      { key: 'section', label: 'Section', type: 'text', required: true, defaultValue: 'Cutting' },
      { key: 'total_strength', label: 'Total Strength', type: 'number' },
      { key: 'present', label: 'Present', type: 'number' },
      { key: 'absent', label: 'Absent', type: 'number' },
      { key: 'leave', label: 'On Leave', type: 'number' },
      { key: 'overtime_workers', label: 'OT Workers', type: 'number' },
      { key: 'absenteeism_pct', label: 'Absenteeism %', type: 'percentage' },
      { key: 'verified_by', label: 'Verified By', type: 'text' },
    ],
  },
  {
    documentType: 'cut_stores_requisition',
    number: 23,
    title: 'Stores Requisition {General Items}',
    linkTo: 'date',
    fields: [
      { key: 'requisition_no', label: 'Requisition No', type: 'text', required: true },
      { key: 'item_description', label: 'Item Description', type: 'textarea', required: true },
      { key: 'qty_requested', label: 'Qty Requested', type: 'number' },
      { key: 'qty_issued', label: 'Qty Issued', type: 'number' },
      { key: 'unit', label: 'Unit', type: 'select', options: [
        { label: 'Pcs', value: 'pcs' }, { label: 'Meters', value: 'meters' },
        { label: 'Kgs', value: 'kgs' }, { label: 'Rolls', value: 'rolls' },
        { label: 'Boxes', value: 'boxes' }, { label: 'Packs', value: 'packs' },
      ]},
      { key: 'requested_by', label: 'Requested By', type: 'text' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'issued_by', label: 'Issued By', type: 'text' },
    ],
  },
  {
    documentType: 'cutting_production_plan',
    number: 24,
    title: 'Cutting Production Plan',
    linkTo: 'style',
    fields: [
      { key: 'plan_ref', label: 'Plan Reference', type: 'text', required: true },
      { key: 'order_qty', label: 'Order Qty', type: 'number' },
      { key: 'planned_cut_qty', label: 'Planned Cut Qty', type: 'number' },
      { key: 'cut_start_date', label: 'Cut Start Date', type: 'date' },
      { key: 'cut_end_date', label: 'Cut End Date', type: 'date' },
      { key: 'no_of_lays', label: 'No. of Lays', type: 'number' },
      { key: 'tables_allocated', label: 'Tables Allocated', type: 'number' },
      { key: 'cutters_allocated', label: 'Cutters Allocated', type: 'number' },
      { key: 'priority', label: 'Priority', type: 'select', options: [
        { label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' },
      ]},
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    documentType: 'cut_style_file',
    number: 25,
    title: 'Style File',
    linkTo: 'style',
    fields: [
      { key: 'file_reference', label: 'File Reference No', type: 'text', required: true },
      { key: 'version', label: 'Version', type: 'text' },
      { key: 'tech_pack_available', label: 'Tech Pack Available', type: 'checkbox' },
      { key: 'cutting_instructions_attached', label: 'Cutting Instructions Attached', type: 'checkbox' },
      { key: 'marker_plan_attached', label: 'Marker Plan Attached', type: 'checkbox' },
      { key: 'fabric_details_attached', label: 'Fabric Details Attached', type: 'checkbox' },
      { key: 'bom_attached', label: 'BOM Attached', type: 'checkbox' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    documentType: 'bulk_cut_procedure',
    number: 26,
    title: 'Bulk Cut Procedure',
    linkTo: 'style',
    fields: [
      { key: 'procedure_ref', label: 'Procedure Reference', type: 'text', required: true },
      { key: 'fabric_type', label: 'Fabric Type', type: 'text' },
      { key: 'spreading_method', label: 'Spreading Method', type: 'select', options: [
        { label: 'Face Up', value: 'face_up' }, { label: 'Face to Face', value: 'face_to_face' },
        { label: 'One Way', value: 'one_way' },
      ]},
      { key: 'cutting_method', label: 'Cutting Method', type: 'select', options: [
        { label: 'Straight Knife', value: 'straight_knife' }, { label: 'Band Knife', value: 'band_knife' },
        { label: 'Die Cut', value: 'die_cut' }, { label: 'Auto Cutter', value: 'auto_cutter' },
      ]},
      { key: 'max_plies', label: 'Max Plies Per Lay', type: 'number' },
      { key: 'shrinkage_allowance', label: 'Shrinkage Allowance %', type: 'percentage' },
      { key: 'end_loss', label: 'End Loss (inches)', type: 'number' },
      { key: 'special_instructions', label: 'Special Instructions', type: 'textarea' },
      { key: 'approved', label: 'Approved', type: 'checkbox' },
    ],
  },
  {
    documentType: 'cutting_instruction',
    number: 27,
    title: 'Cutting Instruction {CI}',
    linkTo: 'style',
    fields: [
      { key: 'ci_no', label: 'CI Number', type: 'text', required: true },
      { key: 'order_qty', label: 'Order Qty', type: 'number' },
      { key: 'size_ratio', label: 'Size Ratio', type: 'text', placeholder: 'S:M:L:XL = 1:2:2:1' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'fabric_code', label: 'Fabric Code', type: 'text' },
      { key: 'marker_length', label: 'Marker Length (m)', type: 'number' },
      { key: 'no_of_plies', label: 'No. of Plies', type: 'number' },
      { key: 'no_of_lays', label: 'No. of Lays', type: 'number' },
      { key: 'total_cut_qty', label: 'Total Cut Qty', type: 'number' },
      { key: 'extra_pct', label: 'Extra %', type: 'percentage' },
      { key: 'issued_by', label: 'Issued By', type: 'text' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
    ],
  },
  {
    documentType: 'distribution_plan',
    number: 28,
    title: 'Distribution Plan',
    linkTo: 'style',
    fields: [
      { key: 'plan_ref', label: 'Plan Reference', type: 'text', required: true },
      { key: 'total_cut_qty', label: 'Total Cut Qty', type: 'number' },
      { key: 'line_1_allocation', label: 'Line 1 Allocation', type: 'number' },
      { key: 'line_2_allocation', label: 'Line 2 Allocation', type: 'number' },
      { key: 'line_3_allocation', label: 'Line 3 Allocation', type: 'number' },
      { key: 'line_4_allocation', label: 'Line 4 Allocation', type: 'number' },
      { key: 'start_date', label: 'Distribution Start Date', type: 'date' },
      { key: 'end_date', label: 'Distribution End Date', type: 'date' },
      { key: 'priority_line', label: 'Priority Line', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    documentType: 'approved_marker',
    number: 29,
    title: 'Approved Marker',
    linkTo: 'style',
    fields: [
      { key: 'marker_ref', label: 'Marker Reference', type: 'text', required: true },
      { key: 'marker_length', label: 'Marker Length (m)', type: 'number' },
      { key: 'marker_width', label: 'Marker Width (inches)', type: 'number' },
      { key: 'marker_efficiency', label: 'Marker Efficiency %', type: 'percentage' },
      { key: 'sizes_in_marker', label: 'Sizes in Marker', type: 'text', placeholder: 'S, M, L, XL' },
      { key: 'pieces_in_marker', label: 'Pieces in Marker', type: 'number' },
      { key: 'cad_system', label: 'CAD System Used', type: 'text' },
      { key: 'checked_by', label: 'Checked By', type: 'text' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'style_cut_plan',
    number: 30,
    title: 'Style Cut Plan',
    linkTo: 'style',
    fields: [
      { key: 'plan_ref', label: 'Plan Reference', type: 'text', required: true },
      { key: 'total_order_qty', label: 'Total Order Qty', type: 'number' },
      { key: 'total_planned_qty', label: 'Total Planned Cut Qty', type: 'number' },
      { key: 'colors', label: 'Colors', type: 'text' },
      { key: 'sizes', label: 'Sizes', type: 'text' },
      { key: 'planned_start', label: 'Planned Start', type: 'date' },
      { key: 'planned_end', label: 'Planned End', type: 'date' },
      { key: 'fabric_requirement', label: 'Fabric Requirement (m)', type: 'number' },
      { key: 'fabric_available', label: 'Fabric Available (m)', type: 'number' },
      { key: 'balance_fabric', label: 'Balance Fabric (m)', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    documentType: 'day_cut_plan',
    number: 31,
    title: 'Day Cut Plan',
    linkTo: 'date',
    fields: [
      { key: 'table_1_style', label: 'Table 1 - Style', type: 'text' },
      { key: 'table_1_qty', label: 'Table 1 - Planned Qty', type: 'number' },
      { key: 'table_2_style', label: 'Table 2 - Style', type: 'text' },
      { key: 'table_2_qty', label: 'Table 2 - Planned Qty', type: 'number' },
      { key: 'table_3_style', label: 'Table 3 - Style', type: 'text' },
      { key: 'table_3_qty', label: 'Table 3 - Planned Qty', type: 'number' },
      { key: 'total_planned', label: 'Total Planned', type: 'number' },
      { key: 'total_actual', label: 'Total Actual', type: 'number' },
      { key: 'variance', label: 'Variance', type: 'number' },
      { key: 'prepared_by', label: 'Prepared By', type: 'text' },
    ],
  },
  {
    documentType: 'fabric_requisition',
    number: 32,
    title: 'Fabric Requisition',
    linkTo: 'style',
    fields: [
      { key: 'requisition_no', label: 'Requisition No', type: 'text', required: true },
      { key: 'fabric_type', label: 'Fabric Type', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'qty_required', label: 'Qty Required (m)', type: 'number' },
      { key: 'qty_issued', label: 'Qty Issued (m)', type: 'number' },
      { key: 'no_of_rolls', label: 'No. of Rolls', type: 'number' },
      { key: 'lot_no', label: 'Lot No', type: 'text' },
      { key: 'requisitioned_by', label: 'Requisitioned By', type: 'text' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'issued_date', label: 'Issue Date', type: 'date' },
    ],
  },
  {
    documentType: 'fabric_receiving',
    number: 33,
    title: 'Fabric Receiving Record',
    linkTo: 'style',
    fields: [
      { key: 'grn_no', label: 'GRN No', type: 'text', required: true },
      { key: 'supplier', label: 'Supplier', type: 'text' },
      { key: 'fabric_type', label: 'Fabric Type', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'no_of_rolls', label: 'No. of Rolls', type: 'number' },
      { key: 'qty_received', label: 'Qty Received (m)', type: 'number' },
      { key: 'inspection_done', label: 'Inspection Done', type: 'checkbox' },
      { key: 'quality_ok', label: 'Quality OK', type: 'checkbox' },
      { key: 'received_by', label: 'Received By', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    documentType: 'layer_sheet',
    number: 34,
    title: 'Layer Sheet',
    linkTo: 'style',
    fields: [
      { key: 'lay_no', label: 'Lay No', type: 'text', required: true },
      { key: 'table_no', label: 'Table No', type: 'text' },
      { key: 'marker_ref', label: 'Marker Reference', type: 'text' },
      { key: 'fabric_type', label: 'Fabric Type', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'no_of_plies', label: 'No. of Plies', type: 'number' },
      { key: 'marker_length', label: 'Marker Length (m)', type: 'number' },
      { key: 'fabric_consumed', label: 'Fabric Consumed (m)', type: 'number' },
      { key: 'end_bits', label: 'End Bits (m)', type: 'number' },
      { key: 'wastage', label: 'Wastage (m)', type: 'number' },
      { key: 'spread_by', label: 'Spread By', type: 'text' },
    ],
  },
  {
    documentType: 'bundle_guide_chart',
    number: 35,
    title: 'Bundle Guide Chart',
    linkTo: 'style',
    fields: [
      { key: 'chart_ref', label: 'Chart Reference', type: 'text', required: true },
      { key: 'bundle_size', label: 'Bundle Size (pcs)', type: 'number' },
      { key: 'total_bundles', label: 'Total Bundles', type: 'number' },
      { key: 'size_breakdown', label: 'Size Breakdown', type: 'textarea', placeholder: 'S=20, M=30, L=25...' },
      { key: 'color_breakdown', label: 'Color Breakdown', type: 'textarea' },
      { key: 'numbering_method', label: 'Numbering Method', type: 'select', options: [
        { label: 'Sequential', value: 'sequential' }, { label: 'Size-wise', value: 'size_wise' },
        { label: 'Color-wise', value: 'color_wise' },
      ]},
      { key: 'prepared_by', label: 'Prepared By', type: 'text' },
      { key: 'verified_by', label: 'Verified By', type: 'text' },
    ],
  },
  {
    documentType: 'day_issuing_plan',
    number: 36,
    title: 'Day Issuing Plan',
    linkTo: 'date',
    fields: [
      { key: 'line_1_style', label: 'Line 1 - Style', type: 'text' },
      { key: 'line_1_qty', label: 'Line 1 - Qty', type: 'number' },
      { key: 'line_2_style', label: 'Line 2 - Style', type: 'text' },
      { key: 'line_2_qty', label: 'Line 2 - Qty', type: 'number' },
      { key: 'line_3_style', label: 'Line 3 - Style', type: 'text' },
      { key: 'line_3_qty', label: 'Line 3 - Qty', type: 'number' },
      { key: 'total_issued', label: 'Total Issued', type: 'number' },
      { key: 'total_balance', label: 'Total Balance', type: 'number' },
      { key: 'prepared_by', label: 'Prepared By', type: 'text' },
    ],
  },
  {
    documentType: 'panel_numbering',
    number: 37,
    title: 'Numbering Of Each Panel',
    linkTo: 'style',
    fields: [
      { key: 'numbering_ref', label: 'Reference No', type: 'text', required: true },
      { key: 'numbering_method', label: 'Numbering Method', type: 'select', options: [
        { label: 'Sticker', value: 'sticker' }, { label: 'Pen Marking', value: 'pen' },
        { label: 'Heat Stamp', value: 'heat_stamp' },
      ]},
      { key: 'panels_per_garment', label: 'Panels Per Garment', type: 'number' },
      { key: 'total_panels', label: 'Total Panels Numbered', type: 'number' },
      { key: 'numbering_start', label: 'Numbering Start', type: 'text' },
      { key: 'numbering_end', label: 'Numbering End', type: 'text' },
      { key: 'verified', label: 'Verified', type: 'checkbox' },
      { key: 'done_by', label: 'Done By', type: 'text' },
    ],
  },
  {
    documentType: 'bundle_card',
    number: 38,
    title: 'Bundle Card',
    linkTo: 'style',
    fields: [
      { key: 'bundle_no', label: 'Bundle No', type: 'text', required: true },
      { key: 'size', label: 'Size', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'qty_in_bundle', label: 'Qty in Bundle', type: 'number' },
      { key: 'lay_no', label: 'Lay No', type: 'text' },
      { key: 'serial_start', label: 'Serial Start', type: 'text' },
      { key: 'serial_end', label: 'Serial End', type: 'text' },
      { key: 'cut_date', label: 'Cut Date', type: 'date' },
      { key: 'issued_to_line', label: 'Issued to Line', type: 'text' },
      { key: 'issued_date', label: 'Issued Date', type: 'date' },
    ],
  },
  {
    documentType: 'bundle_sorting',
    number: 39,
    title: 'Bundle Sorting',
    linkTo: 'style',
    fields: [
      { key: 'sorting_ref', label: 'Sorting Reference', type: 'text', required: true },
      { key: 'total_bundles', label: 'Total Bundles', type: 'number' },
      { key: 'sorted_by_size', label: 'Sorted By Size', type: 'checkbox' },
      { key: 'sorted_by_shade', label: 'Sorted By Shade', type: 'checkbox' },
      { key: 'sorted_by_color', label: 'Sorted By Color', type: 'checkbox' },
      { key: 'shade_groups', label: 'Shade Groups Found', type: 'text' },
      { key: 'mismatched_bundles', label: 'Mismatched Bundles', type: 'number' },
      { key: 'sorted_by', label: 'Sorted By', type: 'text' },
      { key: 'verified_by', label: 'Verified By', type: 'text' },
    ],
  },
  {
    documentType: 'cutting_wip',
    number: 40,
    title: 'Cutting WIP Report',
    linkTo: 'date',
    fields: [
      { key: 'total_cut', label: 'Total Cut (pcs)', type: 'number' },
      { key: 'total_numbered', label: 'Total Numbered', type: 'number' },
      { key: 'total_bundled', label: 'Total Bundled', type: 'number' },
      { key: 'total_issued', label: 'Total Issued to Sewing', type: 'number' },
      { key: 'wip_at_cutting', label: 'WIP at Cutting', type: 'number' },
      { key: 'wip_at_embroidery', label: 'WIP at Embroidery/Print', type: 'number' },
      { key: 'wip_at_fusing', label: 'WIP at Fusing', type: 'number' },
      { key: 'total_wip', label: 'Total WIP', type: 'number' },
      { key: 'prepared_by', label: 'Prepared By', type: 'text' },
    ],
  },
  {
    documentType: 'print_embroidery_records',
    number: 41,
    title: 'Printing Embroidery Sending And Receiving Records',
    linkTo: 'style',
    fields: [
      { key: 'record_ref', label: 'Record Reference', type: 'text', required: true },
      { key: 'process_type', label: 'Process Type', type: 'select', options: [
        { label: 'Printing', value: 'printing' }, { label: 'Embroidery', value: 'embroidery' },
        { label: 'Both', value: 'both' },
      ]},
      { key: 'sent_qty', label: 'Sent Qty', type: 'number' },
      { key: 'sent_date', label: 'Sent Date', type: 'date' },
      { key: 'received_qty', label: 'Received Qty', type: 'number' },
      { key: 'received_date', label: 'Received Date', type: 'date' },
      { key: 'rejected_qty', label: 'Rejected Qty', type: 'number' },
      { key: 'balance_qty', label: 'Balance Qty', type: 'number' },
      { key: 'vendor', label: 'Vendor / Subcontractor', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    documentType: 'cut_issuing_records',
    number: 42,
    title: 'Issuing Records',
    linkTo: 'style',
    fields: [
      { key: 'issue_ref', label: 'Issue Reference', type: 'text', required: true },
      { key: 'issued_to_line', label: 'Issued To Line', type: 'text' },
      { key: 'qty_issued', label: 'Qty Issued', type: 'number' },
      { key: 'bundle_range', label: 'Bundle Range', type: 'text', placeholder: '001 - 050' },
      { key: 'sizes_issued', label: 'Sizes Issued', type: 'text' },
      { key: 'issue_date', label: 'Issue Date', type: 'date' },
      { key: 'received_by', label: 'Received By', type: 'text' },
      { key: 'issued_by', label: 'Issued By', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    documentType: 'cut_goods_return',
    number: 43,
    title: 'Goods Return Records {Fabric & General Items}',
    linkTo: 'date',
    fields: [
      { key: 'return_ref', label: 'Return Reference', type: 'text', required: true },
      { key: 'item_type', label: 'Item Type', type: 'select', options: [
        { label: 'Fabric', value: 'fabric' }, { label: 'General Items', value: 'general' },
      ]},
      { key: 'item_description', label: 'Item Description', type: 'textarea' },
      { key: 'qty_returned', label: 'Qty Returned', type: 'number' },
      { key: 'unit', label: 'Unit', type: 'select', options: [
        { label: 'Meters', value: 'meters' }, { label: 'Kgs', value: 'kgs' },
        { label: 'Pcs', value: 'pcs' }, { label: 'Rolls', value: 'rolls' },
      ]},
      { key: 'reason', label: 'Reason for Return', type: 'textarea' },
      { key: 'returned_by', label: 'Returned By', type: 'text' },
      { key: 'received_by', label: 'Received By (Stores)', type: 'text' },
    ],
  },
  {
    documentType: 'cutting_reconciliation',
    number: 44,
    title: 'Cutting Reconciliation',
    linkTo: 'style',
    fields: [
      { key: 'reconciliation_ref', label: 'Reconciliation Ref', type: 'text', required: true },
      { key: 'order_qty', label: 'Order Qty', type: 'number' },
      { key: 'total_cut', label: 'Total Cut', type: 'number' },
      { key: 'total_issued', label: 'Total Issued to Sewing', type: 'number' },
      { key: 'balance_in_cutting', label: 'Balance in Cutting', type: 'number' },
      { key: 'rejected_panels', label: 'Rejected Panels', type: 'number' },
      { key: 'replaced_panels', label: 'Replaced Panels', type: 'number' },
      { key: 'fabric_consumed', label: 'Fabric Consumed (m)', type: 'number' },
      { key: 'fabric_allocated', label: 'Fabric Allocated (m)', type: 'number' },
      { key: 'fabric_balance', label: 'Fabric Balance (m)', type: 'number' },
      { key: 'wastage_pct', label: 'Wastage %', type: 'percentage' },
      { key: 'reconciled_by', label: 'Reconciled By', type: 'text' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
    ],
  },
];

// All sections config for the MIS navigation
export const MIS_SECTIONS = [
  { key: 'pre_production', label: 'Pre-Production', count: 20, icon: 'FileCheck' },
  { key: 'cutting_production', label: 'Cutting Production', count: 24, icon: 'Scissors' },
  { key: 'cutting_quality', label: 'Cutting Quality', count: 13, icon: 'ShieldCheck' },
  { key: 'sewing_production', label: 'Sewing Production', count: 24, icon: 'Shirt' },
  { key: 'sewing_quality', label: 'Sewing Quality', count: 17, icon: 'Shield' },
  { key: 'finishing_production', label: 'Finishing Production', count: 9, icon: 'PackageCheck' },
  { key: 'finishing_quality', label: 'Finishing Quality', count: 12, icon: 'ClipboardCheck' },
  { key: 'general', label: 'General Activities', count: 2, icon: 'Building' },
  { key: 'stores', label: 'Stores Activities', count: 8, icon: 'Warehouse' },
] as const;
