// Form field configurations for each MIS document type
// Each document type has unique fields stored as JSONB in the `data` column

export interface FormField {
  key: string;
  label: string;
  type: 'text' | 'textarea' | 'number' | 'date' | 'select' | 'checkbox' | 'percentage';
  placeholder?: string;
  options?: { label: string; value: string }[];
  required?: boolean;
  defaultValue?: any;
}

export interface DocumentTypeConfig {
  documentType: string;
  number: number;
  title: string;
  linkTo: 'style' | 'date' | 'line' | 'style_line' | 'none';
  fields: FormField[];
}

const STATUS_OPTIONS = [
  { label: 'Pending', value: 'pending' },
  { label: 'In Progress', value: 'in_progress' },
  { label: 'Completed', value: 'completed' },
  { label: 'Approved', value: 'approved' },
  { label: 'Rejected', value: 'rejected' },
  { label: 'N/A', value: 'na' },
];

const APPROVAL_OPTIONS = [
  { label: 'Pending', value: 'pending' },
  { label: 'Approved', value: 'approved' },
  { label: 'Approved with Comments', value: 'approved_comments' },
  { label: 'Rejected', value: 'rejected' },
];

const GRADE_OPTIONS = [
  { label: 'Pass', value: 'pass' },
  { label: 'Fail', value: 'fail' },
  { label: 'Conditional', value: 'conditional' },
];

export const PRE_PRODUCTION_CONFIGS: DocumentTypeConfig[] = [
  {
    documentType: 'style_file',
    number: 1,
    title: 'Style File',
    linkTo: 'style',
    fields: [
      { key: 'file_reference', label: 'File Reference No', type: 'text', required: true, placeholder: 'SF-001' },
      { key: 'version', label: 'Version', type: 'text', placeholder: 'v1.0' },
      { key: 'tech_pack_received', label: 'Tech Pack Received', type: 'checkbox' },
      { key: 'tech_pack_date', label: 'Tech Pack Received Date', type: 'date' },
      { key: 'bom_prepared', label: 'BOM Prepared', type: 'checkbox' },
      { key: 'operation_breakdown', label: 'Operation Breakdown Done', type: 'checkbox' },
      { key: 'smv_calculated', label: 'SMV Calculated', type: 'checkbox' },
      { key: 'costing_done', label: 'Costing Done', type: 'checkbox' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
      { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional details...' },
    ],
  },
  {
    documentType: 'qc_qi_instructions',
    number: 2,
    title: 'QC / QI Instructions',
    linkTo: 'style',
    fields: [
      { key: 'instruction_ref', label: 'Instruction Reference', type: 'text', required: true, placeholder: 'QCI-001' },
      { key: 'inspection_type', label: 'Inspection Type', type: 'select', options: [
        { label: 'Inline', value: 'inline' }, { label: 'End Line', value: 'endline' },
        { label: 'Final', value: 'final' }, { label: 'AQL', value: 'aql' },
      ]},
      { key: 'critical_points', label: 'Critical Quality Points', type: 'textarea', placeholder: 'List critical quality checkpoints...' },
      { key: 'measurement_points', label: 'Key Measurement Points', type: 'textarea', placeholder: 'List key measurements...' },
      { key: 'tolerance_specs', label: 'Tolerance Specifications', type: 'textarea' },
      { key: 'visual_standards', label: 'Visual Standards Defined', type: 'checkbox' },
      { key: 'distributed_to_lines', label: 'Distributed to Lines', type: 'checkbox' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'approved_sample',
    number: 3,
    title: 'Approved Sample',
    linkTo: 'style',
    fields: [
      { key: 'sample_type', label: 'Sample Type', type: 'select', required: true, options: [
        { label: 'Proto', value: 'proto' }, { label: 'Fit', value: 'fit' },
        { label: 'Size Set', value: 'size_set' }, { label: 'PP Sample', value: 'pp' },
        { label: 'Production', value: 'production' }, { label: 'Shipment', value: 'shipment' },
      ]},
      { key: 'sample_ref', label: 'Sample Reference', type: 'text', placeholder: 'SMPL-001' },
      { key: 'submitted_date', label: 'Submitted Date', type: 'date' },
      { key: 'approval_date', label: 'Approval Date', type: 'date' },
      { key: 'approved_by', label: 'Approved By', type: 'text', placeholder: 'Buyer QA name' },
      { key: 'comments_received', label: 'Buyer Comments', type: 'textarea' },
      { key: 'seal_sample_available', label: 'Seal Sample Available', type: 'checkbox' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'fabric_trim_card',
    number: 4,
    title: 'Approved Fabric Color Continuity Card & Trim Card',
    linkTo: 'style',
    fields: [
      { key: 'fabric_card_ref', label: 'Fabric Card Reference', type: 'text', required: true },
      { key: 'trim_card_ref', label: 'Trim Card Reference', type: 'text', required: true },
      { key: 'fabric_type', label: 'Fabric Type', type: 'text', placeholder: 'e.g., 100% Cotton Denim' },
      { key: 'fabric_color', label: 'Fabric Color', type: 'text' },
      { key: 'color_lot_no', label: 'Color Lot No', type: 'text' },
      { key: 'shade_band', label: 'Shade Band', type: 'select', options: [
        { label: 'A', value: 'A' }, { label: 'B', value: 'B' },
        { label: 'C', value: 'C' }, { label: 'D', value: 'D' },
      ]},
      { key: 'trim_details', label: 'Trim Details', type: 'textarea', placeholder: 'Buttons, zippers, labels...' },
      { key: 'buyer_approved', label: 'Buyer Approved', type: 'checkbox' },
      { key: 'approval_date', label: 'Approval Date', type: 'date' },
      { key: 'approval_status', label: 'Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'lab_test_report',
    number: 5,
    title: 'Lab Test Report Procedure',
    linkTo: 'style',
    fields: [
      { key: 'test_ref', label: 'Test Reference No', type: 'text', required: true },
      { key: 'test_type', label: 'Test Type', type: 'select', options: [
        { label: 'Shrinkage', value: 'shrinkage' }, { label: 'Color Fastness', value: 'color_fastness' },
        { label: 'Tensile Strength', value: 'tensile' }, { label: 'Pilling', value: 'pilling' },
        { label: 'GSM', value: 'gsm' }, { label: 'pH', value: 'ph' },
        { label: 'Dimensional Stability', value: 'dimensional' }, { label: 'Other', value: 'other' },
      ]},
      { key: 'lab_name', label: 'Lab Name', type: 'text', placeholder: 'Testing laboratory' },
      { key: 'test_date', label: 'Test Date', type: 'date' },
      { key: 'test_result', label: 'Test Result', type: 'select', options: GRADE_OPTIONS },
      { key: 'result_details', label: 'Result Details', type: 'textarea' },
      { key: 'buyer_requirement', label: 'Buyer Requirement/Standard', type: 'text' },
      { key: 'certificate_available', label: 'Certificate Available', type: 'checkbox' },
    ],
  },
  {
    documentType: 'fabric_inspection',
    number: 6,
    title: 'Fabric Inspection',
    linkTo: 'style',
    fields: [
      { key: 'inspection_ref', label: 'Inspection Reference', type: 'text', required: true },
      { key: 'fabric_type', label: 'Fabric Type', type: 'text', required: true },
      { key: 'roll_no', label: 'Roll No / Lot No', type: 'text' },
      { key: 'total_meters', label: 'Total Meters Inspected', type: 'number' },
      { key: 'inspection_system', label: 'Inspection System', type: 'select', options: [
        { label: '4-Point System', value: '4_point' }, { label: '10-Point System', value: '10_point' },
      ]},
      { key: 'total_points', label: 'Total Defect Points', type: 'number' },
      { key: 'points_per_100sqm', label: 'Points Per 100 Sq Yards', type: 'number' },
      { key: 'defect_types', label: 'Defect Types Found', type: 'textarea', placeholder: 'Holes, stains, shade variation...' },
      { key: 'pass_fail', label: 'Result', type: 'select', options: GRADE_OPTIONS },
      { key: 'inspected_by', label: 'Inspected By', type: 'text' },
    ],
  },
  {
    documentType: 'trim_inspection',
    number: 7,
    title: 'Trim Inspection',
    linkTo: 'style',
    fields: [
      { key: 'inspection_ref', label: 'Inspection Reference', type: 'text', required: true },
      { key: 'trim_type', label: 'Trim Type', type: 'select', options: [
        { label: 'Button', value: 'button' }, { label: 'Zipper', value: 'zipper' },
        { label: 'Label', value: 'label' }, { label: 'Thread', value: 'thread' },
        { label: 'Rivet', value: 'rivet' }, { label: 'Snap', value: 'snap' },
        { label: 'Elastic', value: 'elastic' }, { label: 'Other', value: 'other' },
      ]},
      { key: 'qty_received', label: 'Qty Received', type: 'number' },
      { key: 'qty_inspected', label: 'Qty Inspected', type: 'number' },
      { key: 'defects_found', label: 'Defects Found', type: 'number' },
      { key: 'defect_description', label: 'Defect Description', type: 'textarea' },
      { key: 'aql_level', label: 'AQL Level', type: 'select', options: [
        { label: '1.0', value: '1.0' }, { label: '1.5', value: '1.5' },
        { label: '2.5', value: '2.5' }, { label: '4.0', value: '4.0' },
      ]},
      { key: 'pass_fail', label: 'Result', type: 'select', options: GRADE_OPTIONS },
      { key: 'inspected_by', label: 'Inspected By', type: 'text' },
    ],
  },
  {
    documentType: 'calibration_equipment',
    number: 8,
    title: 'Calibration Of Measuring Equipment',
    linkTo: 'date',
    fields: [
      { key: 'equipment_name', label: 'Equipment Name', type: 'text', required: true, placeholder: 'e.g., Measuring Tape' },
      { key: 'equipment_id', label: 'Equipment ID / Serial No', type: 'text', required: true },
      { key: 'location', label: 'Location / Department', type: 'text' },
      { key: 'calibration_date', label: 'Calibration Date', type: 'date' },
      { key: 'next_due_date', label: 'Next Due Date', type: 'date' },
      { key: 'calibrated_by', label: 'Calibrated By', type: 'text' },
      { key: 'calibration_result', label: 'Calibration Result', type: 'select', options: GRADE_OPTIONS },
      { key: 'certificate_no', label: 'Certificate No', type: 'text' },
      { key: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  {
    documentType: 'fabric_shrinkage',
    number: 9,
    title: 'Fabric Shrinkage Report',
    linkTo: 'style',
    fields: [
      { key: 'fabric_type', label: 'Fabric Type', type: 'text', required: true },
      { key: 'lot_no', label: 'Lot / Roll No', type: 'text' },
      { key: 'test_method', label: 'Test Method', type: 'select', options: [
        { label: 'Washing', value: 'washing' }, { label: 'Steaming', value: 'steaming' },
        { label: 'Fusing', value: 'fusing' }, { label: 'Dry Clean', value: 'dry_clean' },
      ]},
      { key: 'warp_before', label: 'Warp Before (cm)', type: 'number' },
      { key: 'warp_after', label: 'Warp After (cm)', type: 'number' },
      { key: 'warp_shrinkage', label: 'Warp Shrinkage %', type: 'percentage' },
      { key: 'weft_before', label: 'Weft Before (cm)', type: 'number' },
      { key: 'weft_after', label: 'Weft After (cm)', type: 'number' },
      { key: 'weft_shrinkage', label: 'Weft Shrinkage %', type: 'percentage' },
      { key: 'buyer_tolerance', label: 'Buyer Tolerance %', type: 'percentage' },
      { key: 'result', label: 'Result', type: 'select', options: GRADE_OPTIONS },
    ],
  },
  {
    documentType: 'fabric_segregation',
    number: 10,
    title: 'Fabric Segregation Records',
    linkTo: 'style',
    fields: [
      { key: 'lot_no', label: 'Lot No', type: 'text', required: true },
      { key: 'shade_group', label: 'Shade Group', type: 'select', options: [
        { label: 'A', value: 'A' }, { label: 'B', value: 'B' },
        { label: 'C', value: 'C' }, { label: 'D', value: 'D' },
      ]},
      { key: 'total_rolls', label: 'Total Rolls', type: 'number' },
      { key: 'total_meters', label: 'Total Meters', type: 'number' },
      { key: 'segregated_by_shade', label: 'Segregated By Shade', type: 'checkbox' },
      { key: 'segregated_by_width', label: 'Segregated By Width', type: 'checkbox' },
      { key: 'width_variation', label: 'Width Variation (inches)', type: 'text' },
      { key: 'shade_remarks', label: 'Shade Remarks', type: 'textarea' },
      { key: 'segregated_by', label: 'Segregated By', type: 'text' },
    ],
  },
  {
    documentType: 'cutting_pattern_approval',
    number: 11,
    title: 'Cutting Pattern Approval',
    linkTo: 'style',
    fields: [
      { key: 'pattern_ref', label: 'Pattern Reference', type: 'text', required: true },
      { key: 'sizes', label: 'Sizes', type: 'text', placeholder: 'S, M, L, XL, XXL' },
      { key: 'pattern_maker', label: 'Pattern Maker', type: 'text' },
      { key: 'grading_done', label: 'Grading Done', type: 'checkbox' },
      { key: 'notches_checked', label: 'Notches Checked', type: 'checkbox' },
      { key: 'grain_lines_checked', label: 'Grain Lines Checked', type: 'checkbox' },
      { key: 'seam_allowance_verified', label: 'Seam Allowance Verified', type: 'checkbox' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'approval_date', label: 'Approval Date', type: 'date' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'finish_pattern_marking',
    number: 12,
    title: 'Finish Pattern And Marking Board Approvals',
    linkTo: 'style',
    fields: [
      { key: 'pattern_ref', label: 'Finish Pattern Reference', type: 'text', required: true },
      { key: 'marking_board_ref', label: 'Marking Board Reference', type: 'text' },
      { key: 'sizes_checked', label: 'Sizes Checked', type: 'text', placeholder: 'S, M, L, XL' },
      { key: 'button_marking', label: 'Button Marking Verified', type: 'checkbox' },
      { key: 'pocket_placement', label: 'Pocket Placement Verified', type: 'checkbox' },
      { key: 'label_placement', label: 'Label Placement Verified', type: 'checkbox' },
      { key: 'embroidery_placement', label: 'Embroidery Placement Verified', type: 'checkbox' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'approval_date', label: 'Approval Date', type: 'date' },
      { key: 'approval_status', label: 'Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'line_sample',
    number: 13,
    title: 'Line Sample',
    linkTo: 'style_line',
    fields: [
      { key: 'sample_ref', label: 'Sample Reference', type: 'text', required: true },
      { key: 'sample_size', label: 'Sample Size', type: 'text', placeholder: 'e.g., M' },
      { key: 'sample_qty', label: 'Sample Qty', type: 'number' },
      { key: 'prepared_date', label: 'Prepared Date', type: 'date' },
      { key: 'checked_by_qc', label: 'Checked by QC', type: 'checkbox' },
      { key: 'checked_by_ie', label: 'Checked by IE', type: 'checkbox' },
      { key: 'measurement_ok', label: 'Measurement OK', type: 'checkbox' },
      { key: 'construction_ok', label: 'Construction OK', type: 'checkbox' },
      { key: 'buyer_comments', label: 'Buyer Comments', type: 'textarea' },
      { key: 'approval_status', label: 'Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
  {
    documentType: 'measurement_sheet',
    number: 14,
    title: 'Measurement Sheet',
    linkTo: 'style',
    fields: [
      { key: 'measurement_ref', label: 'Measurement Ref', type: 'text', required: true },
      { key: 'size', label: 'Size', type: 'text', required: true, placeholder: 'e.g., M' },
      { key: 'tolerance', label: 'Tolerance (+/-)', type: 'text', placeholder: 'e.g., 0.5 inch' },
      { key: 'chest', label: 'Chest', type: 'text' },
      { key: 'waist', label: 'Waist', type: 'text' },
      { key: 'hip', label: 'Hip', type: 'text' },
      { key: 'inseam', label: 'Inseam', type: 'text' },
      { key: 'outseam', label: 'Outseam', type: 'text' },
      { key: 'body_length', label: 'Body Length', type: 'text' },
      { key: 'sleeve_length', label: 'Sleeve Length', type: 'text' },
      { key: 'shoulder', label: 'Shoulder', type: 'text' },
      { key: 'thigh', label: 'Thigh', type: 'text' },
      { key: 'knee', label: 'Knee', type: 'text' },
      { key: 'bottom_opening', label: 'Bottom Opening', type: 'text' },
      { key: 'additional_measurements', label: 'Additional Measurements', type: 'textarea' },
      { key: 'verified_by', label: 'Verified By', type: 'text' },
    ],
  },
  {
    documentType: 'critical_operation',
    number: 15,
    title: 'Critical Operation Identification',
    linkTo: 'style',
    fields: [
      { key: 'operation_1', label: 'Critical Operation 1', type: 'text', placeholder: 'e.g., Front pocket attach' },
      { key: 'machine_1', label: 'Machine Type 1', type: 'text' },
      { key: 'operation_2', label: 'Critical Operation 2', type: 'text' },
      { key: 'machine_2', label: 'Machine Type 2', type: 'text' },
      { key: 'operation_3', label: 'Critical Operation 3', type: 'text' },
      { key: 'machine_3', label: 'Machine Type 3', type: 'text' },
      { key: 'operation_4', label: 'Critical Operation 4', type: 'text' },
      { key: 'machine_4', label: 'Machine Type 4', type: 'text' },
      { key: 'operation_5', label: 'Critical Operation 5', type: 'text' },
      { key: 'machine_5', label: 'Machine Type 5', type: 'text' },
      { key: 'skill_required', label: 'Special Skill Required', type: 'textarea' },
      { key: 'training_done', label: 'Training Done', type: 'checkbox' },
    ],
  },
  {
    documentType: 'line_layout_manpower',
    number: 16,
    title: 'Line Layout And Manpower Allocation',
    linkTo: 'style_line',
    fields: [
      { key: 'layout_ref', label: 'Layout Reference', type: 'text', required: true },
      { key: 'total_operations', label: 'Total Operations', type: 'number' },
      { key: 'total_operators', label: 'Total Operators', type: 'number' },
      { key: 'total_helpers', label: 'Total Helpers', type: 'number' },
      { key: 'total_machines', label: 'Total Machines', type: 'number' },
      { key: 'smv', label: 'Target SMV', type: 'number' },
      { key: 'target_output', label: 'Target Output/Hour', type: 'number' },
      { key: 'bottleneck_identified', label: 'Bottleneck Operations Identified', type: 'textarea' },
      { key: 'layout_approved', label: 'Layout Approved', type: 'checkbox' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
    ],
  },
  {
    documentType: 'fabric_trim_status',
    number: 17,
    title: 'Fabric & Trim Status Report',
    linkTo: 'style',
    fields: [
      { key: 'fabric_ordered', label: 'Fabric Ordered (meters)', type: 'number' },
      { key: 'fabric_received', label: 'Fabric Received (meters)', type: 'number' },
      { key: 'fabric_inspected', label: 'Fabric Inspected (meters)', type: 'number' },
      { key: 'fabric_status', label: 'Fabric Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'trim_ordered', label: 'Total Trim Items Ordered', type: 'number' },
      { key: 'trim_received', label: 'Trim Items Received', type: 'number' },
      { key: 'trim_pending', label: 'Trim Items Pending', type: 'number' },
      { key: 'trim_status', label: 'Trim Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'shortage_details', label: 'Shortage Details', type: 'textarea' },
      { key: 'eta_pending', label: 'ETA for Pending Items', type: 'date' },
    ],
  },
  {
    documentType: 'pp_meeting',
    number: 18,
    title: 'PP Meeting',
    linkTo: 'style',
    fields: [
      { key: 'meeting_date', label: 'Meeting Date', type: 'date', required: true },
      { key: 'meeting_ref', label: 'Meeting Reference', type: 'text' },
      { key: 'attendees', label: 'Attendees', type: 'textarea', placeholder: 'Names and designations...' },
      { key: 'fabric_status_reviewed', label: 'Fabric Status Reviewed', type: 'checkbox' },
      { key: 'trim_status_reviewed', label: 'Trim Status Reviewed', type: 'checkbox' },
      { key: 'sample_reviewed', label: 'Sample Reviewed', type: 'checkbox' },
      { key: 'production_plan_discussed', label: 'Production Plan Discussed', type: 'checkbox' },
      { key: 'quality_points_discussed', label: 'Quality Points Discussed', type: 'checkbox' },
      { key: 'action_points', label: 'Action Points', type: 'textarea', placeholder: 'List action items...' },
      { key: 'minutes', label: 'Meeting Minutes', type: 'textarea' },
      { key: 'next_meeting_date', label: 'Next Meeting Date', type: 'date' },
    ],
  },
  {
    documentType: 'pp_checklist',
    number: 19,
    title: 'PP Check List',
    linkTo: 'style',
    fields: [
      { key: 'tech_pack_available', label: 'Tech Pack Available', type: 'checkbox' },
      { key: 'approved_sample_available', label: 'Approved Sample Available', type: 'checkbox' },
      { key: 'fabric_approved', label: 'Fabric Approved', type: 'checkbox' },
      { key: 'trims_approved', label: 'Trims Approved', type: 'checkbox' },
      { key: 'pattern_approved', label: 'Pattern Approved', type: 'checkbox' },
      { key: 'measurement_spec_available', label: 'Measurement Spec Available', type: 'checkbox' },
      { key: 'shrinkage_report_done', label: 'Shrinkage Report Done', type: 'checkbox' },
      { key: 'lab_test_done', label: 'Lab Test Done', type: 'checkbox' },
      { key: 'bom_confirmed', label: 'BOM Confirmed', type: 'checkbox' },
      { key: 'line_layout_ready', label: 'Line Layout Ready', type: 'checkbox' },
      { key: 'manpower_allocated', label: 'Manpower Allocated', type: 'checkbox' },
      { key: 'risk_assessment', label: 'Risk Assessment Done', type: 'checkbox' },
      { key: 'pp_meeting_done', label: 'PP Meeting Done', type: 'checkbox' },
      { key: 'overall_readiness', label: 'Overall Readiness', type: 'percentage' },
      { key: 'checklist_approved_by', label: 'Approved By', type: 'text' },
    ],
  },
  {
    documentType: 'size_set_pilot_cut',
    number: 20,
    title: 'Size Set / Pilot Cut Approval',
    linkTo: 'style',
    fields: [
      { key: 'pilot_ref', label: 'Pilot Cut Reference', type: 'text', required: true },
      { key: 'sizes_cut', label: 'Sizes Cut', type: 'text', placeholder: 'S, M, L, XL' },
      { key: 'qty_per_size', label: 'Qty Per Size', type: 'number' },
      { key: 'cut_date', label: 'Cut Date', type: 'date' },
      { key: 'fabric_used', label: 'Fabric Used', type: 'text' },
      { key: 'sewing_completed', label: 'Sewing Completed', type: 'checkbox' },
      { key: 'measurement_checked', label: 'Measurement Checked', type: 'checkbox' },
      { key: 'fit_approved', label: 'Fit Approved', type: 'checkbox' },
      { key: 'construction_approved', label: 'Construction Approved', type: 'checkbox' },
      { key: 'wash_test_done', label: 'Wash Test Done', type: 'checkbox' },
      { key: 'defects_found', label: 'Defects Found', type: 'textarea' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'approval_status', label: 'Status', type: 'select', options: APPROVAL_OPTIONS },
    ],
  },
];

// All sections config for the MIS navigation
export const MIS_SECTIONS = [
  { key: 'pre_production', label: 'Pre-Production', count: 20, icon: 'FileCheck' },
  { key: 'cutting_production', label: 'Cutting Production', count: 24, icon: 'Scissors' },
  { key: 'cutting_quality', label: 'Cutting Quality', count: 13, icon: 'ShieldCheck' },
  { key: 'sewing_production', label: 'Sewing Production', count: 24, icon: 'Shirt' },
  { key: 'sewing_quality', label: 'Sewing Quality', count: 17, icon: 'Shield' },
  { key: 'finishing_production', label: 'Finishing Production', count: 9, icon: 'PackageCheck' },
  { key: 'finishing_quality', label: 'Finishing Quality', count: 12, icon: 'ClipboardCheck' },
  { key: 'general', label: 'General Activities', count: 2, icon: 'Building' },
  { key: 'stores', label: 'Stores Activities', count: 8, icon: 'Warehouse' },
] as const;
